export interface TeamTechnician {
  id: string;
  emp_id: string;
  name: string;
  displayName: string;
  role: string;
  tag?: string;
  department: string;
  phone: string;
  email: string;
  status: "online" | "busy" | "offline";
  startDate: string;
  experienceYears: string;
  skills: string[];
  avatarColor: string;
  avatarChar: string;
  jobsStats: {
    total: number;
    assigned: number;   // รับงาน (blue)
    done: number;       // เสร็จสิ้น (green)
    inProgress: number; // ดำเนินการ (orange)
  };
  categoryStats: {
    generalRepair: number; // งานซ่อมทั่วไป
    hvac: number;          // ระบบปรับอากาศ (HVAC)
    installation: number;  // งานติดตั้ง
    inspection: number;    // งานตรวจสอบ
  };
}

export interface TechnicianJobItem {
  id: string;
  clientOrLocation: string;
  detail: string;
  status: "assigned" | "doing" | "complete";
  assignedDate: string;
  updatedDate: string;
}

export const MOCK_TEAM_TECHNICIANS: TeamTechnician[] = [
  {
    id: "TECH001",
    emp_id: "TEC0001",
    name: "สมศักดิ์ ช่างไฟ",
    displayName: "สมศักดิ์",
    role: "ช่างไฟ",
    tag: "ELEC",
    department: "งานระบบไฟฟ้า",
    phone: "081-111-2233",
    email: "somsak@company.com",
    status: "online",
    startDate: "15 มี.ค. 2563",
    experienceYears: "3 ปี 4 เดือน",
    skills: ["ซ่อมบำรุงระบบไฟฟ้าโรงงาน", "ตรวจเช็คตู้ MDB และเบรกเกอร์", "เดินสายไฟและหม้อแปลง"],
    avatarColor: "bg-blue-600",
    avatarChar: "ส",
    jobsStats: { total: 6, assigned: 3, done: 2, inProgress: 1 },
    categoryStats: { generalRepair: 4, hvac: 0, installation: 2, inspection: 0 },
  },
  {
    id: "TECH002",
    emp_id: "TEC0002",
    name: "วิษณุ ช่างกล",
    displayName: "วิษณุ",
    role: "ช่างกล",
    tag: "MECH",
    department: "งานระบบเครื่องกล",
    phone: "081-222-3344",
    email: "witsanu@company.com",
    status: "online",
    startDate: "10 ก.ค. 2563",
    experienceYears: "3 ปี 0 เดือน",
    skills: ["ซ่อมเครื่องกลและมอเตอร์", "ระบบสายพานลำเลียง", "การตั้งศูนย์เพลาและเกียร์"],
    avatarColor: "bg-indigo-600",
    avatarChar: "ว",
    jobsStats: { total: 5, assigned: 2, done: 2, inProgress: 1 },
    categoryStats: { generalRepair: 3, hvac: 1, installation: 1, inspection: 0 },
  },
  {
    id: "TECH004",
    emp_id: "TEC0012",
    name: "อานนท์ ใจดี",
    displayName: "อานนท์",
    role: "ช่างแอร์ (HVAC)",
    tag: "HVAC",
    department: "งานระบบปรับอากาศ",
    phone: "081-234-5678",
    email: "anont@company.com",
    status: "online",
    startDate: "12 ม.ค. 2564",
    experienceYears: "2 ปี 6 เดือน",
    skills: [
      "ซ่อมบำรุงระบบปรับอากาศ (แอร์บ้าน/แอร์โรงงาน)",
      "ตรวจเช็คระบบทำความเย็น",
      "ยกติดตั้งและเดินท่อแอร์",
    ],
    avatarColor: "bg-sky-600",
    avatarChar: "อ",
    jobsStats: { total: 4, assigned: 2, done: 1, inProgress: 1 },
    categoryStats: { generalRepair: 3, hvac: 2, installation: 1, inspection: 0 },
  },
  {
    id: "TECH006",
    emp_id: "TEC0006",
    name: "เกรียงไกร ช่างเชื่อม & โครงสร้าง",
    displayName: "เกรียงไกร",
    role: "ช่างเชื่อม & โครงสร้าง",
    tag: "WELD",
    department: "งานโครงสร้างและโลหะ",
    phone: "081-444-5566",
    email: "kriangkrai@company.com",
    status: "online",
    startDate: "20 ส.ค. 2564",
    experienceYears: "2 ปี 0 เดือน",
    skills: ["งานเชื่อมอาร์ก TIG/MIG", "ดัดแปลงโครงสร้างเหล็ก", "ซ่อมบำรุงแท่นเครื่องจักร"],
    avatarColor: "bg-amber-600",
    avatarChar: "ก",
    jobsStats: { total: 3, assigned: 1, done: 1, inProgress: 1 },
    categoryStats: { generalRepair: 2, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH005",
    emp_id: "TEC0005",
    name: "นครินทร์ ช่างอิเล็กทรอนิกส์ & PLC",
    displayName: "นครินทร์",
    role: "ช่างอิเล็กทรอนิกส์ & PLC",
    tag: "PLC",
    department: "งานระบบอัตโนมัติ",
    phone: "081-555-6677",
    email: "nakarin@company.com",
    status: "online",
    startDate: "5 ม.ค. 2565",
    experienceYears: "1 ปี 6 เดือน",
    skills: ["เขียนโปรแกรม PLC Ladder", "ซ่อมบอร์ดคอนโทรลเลอร์", "สอบเทียบเซนเซอร์อุตสาหกรรม"],
    avatarColor: "bg-purple-600",
    avatarChar: "น",
    jobsStats: { total: 2, assigned: 1, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH003",
    emp_id: "TEC0003",
    name: "สุรพล ช่างประปา",
    displayName: "สุรพล",
    role: "ช่างประปา",
    tag: "PLUMB",
    department: "งานระบบสุขาภิบาล",
    phone: "081-333-4455",
    email: "surapol@company.com",
    status: "online",
    startDate: "1 ก.พ. 2564",
    experienceYears: "2 ปี 5 เดือน",
    skills: ["ซ่อมท่อแรงดันสูง", "ระบบปั๊มน้ำ Booster", "ตรวจเช็ควาล์วควบคุมน้ำ"],
    avatarColor: "bg-blue-500",
    avatarChar: "ส",
    jobsStats: { total: 2, assigned: 1, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 1 },
  },
  {
    id: "TECH007",
    emp_id: "TEC0007",
    name: "ไพศาล ช่างทั่วไป",
    displayName: "ไพศาล",
    role: "ช่างทั่วไป",
    tag: "GEN",
    department: "งานบริการอาคาร",
    phone: "081-666-7788",
    email: "phaisan@company.com",
    status: "online",
    startDate: "15 พ.ย. 2564",
    experienceYears: "1 ปี 8 เดือน",
    skills: ["ซ่อมบำรุงอาคารทั่วไป", "งานประตูหน้าต่างและลูกบิด", "ตรวจเช็คสภาพห้องปฏิบัติงาน"],
    avatarColor: "bg-pink-600",
    avatarChar: "ไ",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH008",
    emp_id: "TEC0008",
    name: "ธนวัฒน์ ช่างเครื่องจักร",
    displayName: "ธนวัฒน์",
    role: "ช่างเครื่องจักร",
    tag: "MACH",
    department: "งานซ่อมบำรุงเครื่องจักร",
    phone: "081-777-8899",
    email: "thanawat@company.com",
    status: "online",
    startDate: "10 ม.ค. 2565",
    experienceYears: "1 ปี 6 เดือน",
    skills: ["เครื่องกลึง CNC และ Milling", "ระบบหล่อลื่นไฮดรอลิก", "เปลี่ยนตลับลูกปืนเพลา"],
    avatarColor: "bg-emerald-600",
    avatarChar: "ธ",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH009",
    emp_id: "TEC0009",
    name: "ชัยวัฒน์ ช่างก่อสร้าง",
    displayName: "ชัยวัฒน์",
    role: "ช่างก่อสร้าง",
    tag: "CIVIL",
    department: "งานโยธาและก่อสร้าง",
    phone: "081-888-9900",
    email: "chaiwat@company.com",
    status: "online",
    startDate: "1 พ.ค. 2565",
    experienceYears: "1 ปี 2 เดือน",
    skills: ["ซ่อมแซมพื้นและผนังโรงงาน", "งานกันซึมดาดฟ้า", "ปรับปรุงพื้นที่ผลิต"],
    avatarColor: "bg-green-600",
    avatarChar: "ช",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH010",
    emp_id: "TEC0010",
    name: "วินัย ช่างสี",
    displayName: "วินัย",
    role: "ช่างสี",
    tag: "PAINT",
    department: "งานสีและเคลือบผิว",
    phone: "081-999-0011",
    email: "winai@company.com",
    status: "online",
    startDate: "15 มิ.ย. 2565",
    experienceYears: "1 ปี 1 เดือน",
    skills: ["งานพ่นสีอีพ็อกซี่พื้นโรงงาน", "ทาสีกันสนิมโครงสร้างเหล็ก", "งานขัดผิวชิ้นงาน"],
    avatarColor: "bg-fuchsia-600",
    avatarChar: "ว",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH011",
    emp_id: "TEC0011",
    name: "กิตติศักดิ์ ช่างยนต์",
    displayName: "กิตติศักดิ์",
    role: "ช่างยนต์",
    tag: "AUTO",
    department: "งานยานพาหนะและโฟล์กลิฟต์",
    phone: "081-123-4567",
    email: "kittisak@company.com",
    status: "online",
    startDate: "1 ก.ย. 2564",
    experienceYears: "1 ปี 10 เดือน",
    skills: ["ซ่อมบำรุงรถโฟล์กลิฟต์ไฟฟ้า", "ระบบเบรกและเกียร์", "เครื่องยนต์ดีเซล"],
    avatarColor: "bg-orange-600",
    avatarChar: "ก",
    jobsStats: { total: 2, assigned: 1, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH012",
    emp_id: "TEC0013",
    name: "ประเสริฐ ช่างไฮดรอลิก",
    displayName: "ประเสริฐ",
    role: "ช่างไฮดรอลิก",
    tag: "HYD",
    department: "งานระบบไฮดรอลิก",
    phone: "081-234-8901",
    email: "prasert@company.com",
    status: "online",
    startDate: "15 ต.ค. 2564",
    experienceYears: "1 ปี 9 เดือน",
    skills: ["ระบบกระบอกสูบไฮดรอลิก", "เปลี่ยนซีลและน้ำมันไฮดรอลิก", "ตั้งค่า Pressure Relief Valve"],
    avatarColor: "bg-teal-600",
    avatarChar: "ป",
    jobsStats: { total: 2, assigned: 1, done: 0, inProgress: 1 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 1 },
  },
  {
    id: "TECH013",
    emp_id: "TEC0014",
    name: "ธีรพงษ์ ช่างนิวแมติกส์",
    displayName: "ธีรพงษ์",
    role: "ช่างนิวแมติกส์",
    tag: "PNEU",
    department: "งานระบบนิวแมติกส์",
    phone: "081-345-6789",
    email: "theerapong@company.com",
    status: "online",
    startDate: "1 พ.ย. 2564",
    experienceYears: "1 ปี 8 เดือน",
    skills: ["ระบบลมและ Solenoid Valve", "ปั๊มลม Screw Compressor", "ระบบดูดสุญญากาศ"],
    avatarColor: "bg-cyan-600",
    avatarChar: "ธ",
    jobsStats: { total: 2, assigned: 1, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH014",
    emp_id: "TEC0015",
    name: "ชาญชัย ช่างแอร์",
    displayName: "ชาญชัย",
    role: "ช่างแอร์",
    tag: "HVAC",
    department: "งานระบบปรับอากาศ",
    phone: "081-456-7890",
    email: "chanchai@company.com",
    status: "online",
    startDate: "15 ธ.ค. 2564",
    experienceYears: "1 ปี 7 เดือน",
    skills: ["ล้างแอร์ AHU และ FCU", "เติมน้ำยาแอร์ R32/R410a", "เปลี่ยนคอมเพรสเซอร์"],
    avatarColor: "bg-sky-500",
    avatarChar: "ช",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 1, installation: 0, inspection: 0 },
  },
  {
    id: "TECH015",
    emp_id: "TEC0016",
    name: "อนุรักษ์ ช่างเครื่องเสียง",
    displayName: "อนุรักษ์",
    role: "ช่างระบบเสียง",
    tag: "AV",
    department: "งานระบบสื่อสาร",
    phone: "081-567-8901",
    email: "anurak@company.com",
    status: "online",
    startDate: "1 ม.ค. 2565",
    experienceYears: "1 ปี 6 เดือน",
    skills: ["ระบบประกาศเสียงตามสาย (PA)", "ระบบเสียงห้องประชุม", "เครื่องขยายเสียงและไมโครโฟน"],
    avatarColor: "bg-violet-600",
    avatarChar: "อ",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH016",
    emp_id: "TEC0017",
    name: "วีระ ช่างไฟฟ้ากำลัง",
    displayName: "วีระ",
    role: "ช่างไฟฟ้ากำลัง",
    tag: "POWER",
    department: "งานระบบไฟฟ้า",
    phone: "081-678-9012",
    email: "weera@company.com",
    status: "online",
    startDate: "1 ก.พ. 2565",
    experienceYears: "1 ปี 5 เดือน",
    skills: ["ระบบไฟฟ้าแรงสูง 22kV", "สวิตช์เกียร์และคาปาซิเตอร์แบงก์", "ระบบ UPS โรงงาน"],
    avatarColor: "bg-blue-700",
    avatarChar: "ว",
    jobsStats: { total: 1, assigned: 0, done: 0, inProgress: 1 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH017",
    emp_id: "TEC0018",
    name: "ภานุวัฒน์ ช่างกลโรงงาน",
    displayName: "ภานุวัฒน์",
    role: "ช่างกลโรงงาน",
    tag: "MACH",
    department: "งานระบบเครื่องกล",
    phone: "081-789-0123",
    email: "phanuwat@company.com",
    status: "online",
    startDate: "15 มี.ค. 2565",
    experienceYears: "1 ปี 4 เดือน",
    skills: ["งานกลึง เจียระไน กัดชิ้นงาน", "ผลิตชิ้นส่วนอะไหล่ทดแทน", "งานตั้งระยะ Clearance"],
    avatarColor: "bg-indigo-700",
    avatarChar: "ภ",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH018",
    emp_id: "TEC0019",
    name: "อุดม ช่างบำรุงรักษา",
    displayName: "อุดม",
    role: "ช่างบำรุงรักษา",
    tag: "PM",
    department: "งานบำรุงรักษาเชิงป้องกัน",
    phone: "081-890-1234",
    email: "udom@company.com",
    status: "online",
    startDate: "1 เม.ย. 2565",
    experienceYears: "1 ปี 3 เดือน",
    skills: ["การตรวจวัดการสั่นสะเทือน (Vibration)", "กล้องถ่ายภาพความร้อน (Thermoscan)", "การอัดจาระบีตามรอบ"],
    avatarColor: "bg-emerald-700",
    avatarChar: "อ",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 0, inspection: 1 },
  },
  {
    id: "TECH019",
    emp_id: "TEC0020",
    name: "ศักดิ์ดา ช่างโลหะ",
    displayName: "ศักดิ์ดา",
    role: "ช่างโลหะ",
    tag: "METAL",
    department: "งานโครงสร้างและโลหะ",
    phone: "081-901-2345",
    email: "sakda@company.com",
    status: "online",
    startDate: "1 พ.ค. 2565",
    experienceYears: "1 ปี 2 เดือน",
    skills: ["งานตัดพับโลหะแผ่น", "งานทำ Guard ป้องกันเครื่องจักร", "งานขึ้นรูปท่อระบายอากาศ"],
    avatarColor: "bg-amber-700",
    avatarChar: "ศ",
    jobsStats: { total: 1, assigned: 0, done: 0, inProgress: 1 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH020",
    emp_id: "TEC0021",
    name: "นเรศ ช่างเครน & ลิฟต์",
    displayName: "นเรศ",
    role: "ช่างเครน & ลิฟต์",
    tag: "CRANE",
    department: "งานระบบลำเลียง",
    phone: "081-012-3456",
    email: "nares@company.com",
    status: "online",
    startDate: "15 มิ.ย. 2565",
    experienceYears: "1 ปี 1 เดือน",
    skills: ["ตรวจเช็คสลิงและรอกเครน", "ลิฟต์ส่งของโรงงาน", "ระบบลิมิตสวิตช์ความปลอดภัย"],
    avatarColor: "bg-rose-600",
    avatarChar: "น",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 0, inspection: 1 },
  },
  {
    id: "TECH021",
    emp_id: "TEC0022",
    name: "สมคิด ช่างเน็ตเวิร์ก",
    displayName: "สมคิด",
    role: "ช่างไอที",
    tag: "IT",
    department: "งานระบบเทคโนโลยี",
    phone: "081-123-9876",
    email: "somkid@company.com",
    status: "online",
    startDate: "1 ก.ค. 2565",
    experienceYears: "1 ปี 0 เดือน",
    skills: ["สายแลนและไฟเบอร์ออปติก", "ระบบ Wi-Fi และสวิตช์เครือข่าย", "กล้องวงจรปิด CCTV"],
    avatarColor: "bg-slate-700",
    avatarChar: "ส",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 1, inspection: 0 },
  },
  {
    id: "TECH022",
    emp_id: "TEC0023",
    name: "ทรงพล ช่าง PLC",
    displayName: "ทรงพล",
    role: "ช่าง PLC",
    tag: "PLC",
    department: "งานระบบอัตโนมัติ",
    phone: "081-234-0987",
    email: "songpol@company.com",
    status: "online",
    startDate: "15 ส.ค. 2565",
    experienceYears: "0 ปี 11 เดือน",
    skills: ["Siemens & Mitsubishi PLC", "หน้าจอสัมผัส HMI", "ระบบควบคุม Servo Motor"],
    avatarColor: "bg-purple-700",
    avatarChar: "ท",
    jobsStats: { total: 1, assigned: 0, done: 0, inProgress: 1 },
    categoryStats: { generalRepair: 1, hvac: 0, installation: 0, inspection: 0 },
  },
  {
    id: "TECH023",
    emp_id: "TEC0024",
    name: "ยุทธนา ช่างระบบบำบัด",
    displayName: "ยุทธนา",
    role: "ช่างสิ่งแวดล้อม",
    tag: "ENV",
    department: "งานระบบสุขาภิบาล",
    phone: "081-345-1098",
    email: "yutthana@company.com",
    status: "online",
    startDate: "1 ก.ย. 2565",
    experienceYears: "0 ปี 10 เดือน",
    skills: ["ระบบบำบัดน้ำเสีย", "เครื่องเติมอากาศ Aerator", "ระบบตกตะกอนเคมี"],
    avatarColor: "bg-teal-700",
    avatarChar: "ย",
    jobsStats: { total: 1, assigned: 1, done: 0, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 0, inspection: 1 },
  },
  {
    id: "TECH024",
    emp_id: "TEC0025",
    name: "พิพัฒน์ ช่างความปลอดภัย",
    displayName: "พิพัฒน์",
    role: "ช่างเซฟตี้",
    tag: "SAFETY",
    department: "งานความปลอดภัย",
    phone: "081-456-2109",
    email: "phiphat@company.com",
    status: "online",
    startDate: "1 ต.ค. 2565",
    experienceYears: "0 ปี 9 เดือน",
    skills: ["ระบบดับเพลิงและสปริงเกลอร์", "ถังดับเพลิงและปั๊มดับเพลิง", "สัญญาณเตือนไฟไหม้ Fire Alarm"],
    avatarColor: "bg-red-600",
    avatarChar: "พ",
    jobsStats: { total: 1, assigned: 0, done: 1, inProgress: 0 },
    categoryStats: { generalRepair: 0, hvac: 0, installation: 0, inspection: 1 },
  },
];

// Jobs specific for Anont (TECH004) as shown in Image 2
export const MOCK_ANONT_JOBS: TechnicianJobItem[] = [
  {
    id: "JOB-2025-001",
    clientOrLocation: "บริษัท ศรีสะเกษเทคโนโลยี",
    detail: "ตรวจเช็คแอร์ห้องประชุม (HVAC)",
    status: "doing",
    assignedDate: "12 พ.ค. 2568",
    updatedDate: "14 พ.ค. 2568 10:24",
  },
  {
    id: "JOB-2025-002",
    clientOrLocation: "ร้านกาแฟ อุ่นใจ",
    detail: "ซ่อมแอร์ร้านกาแฟ",
    status: "assigned",
    assignedDate: "10 พ.ค. 2568",
    updatedDate: "10 พ.ค. 2568 16:37",
  },
  {
    id: "JOB-2025-003",
    clientOrLocation: "โรงพยาบาลศรีสะเกษ",
    detail: "ล้างแอร์ระบบห้องผู้ป่วย",
    status: "complete",
    assignedDate: "5 พ.ค. 2568",
    updatedDate: "7 พ.ค. 2568 14:12",
  },
  {
    id: "JOB-2025-004",
    clientOrLocation: "บริษัท ไทยรุ่งเรือง จำกัด",
    detail: "ติดตั้งแอร์สำนักงาน",
    status: "doing",
    assignedDate: "2 พ.ค. 2568",
    updatedDate: "6 พ.ค. 2568 09:45",
  },
  {
    id: "JOB-2025-005",
    clientOrLocation: "ห้างสรรพสินค้าเมืองศรี",
    detail: "ตรวจเช็คระบบปรับอากาศ",
    status: "assigned",
    assignedDate: "28 เม.ย. 2568",
    updatedDate: "28 เม.ย. 2568 15:33",
  },
  {
    id: "JOB-2025-006",
    clientOrLocation: "โรงงานน้ำตาลศรีสะเกษ",
    detail: "ซ่อมแอร์ไลน์ผลิต",
    status: "doing",
    assignedDate: "25 เม.ย. 2568",
    updatedDate: "26 เม.ย. 2568 11:20",
  },
];

// Helper to get jobs for any technician
export function getTechnicianJobs(techId: string): TechnicianJobItem[] {
  if (techId === "TECH004") {
    return MOCK_ANONT_JOBS;
  }
  const tech = MOCK_TEAM_TECHNICIANS.find((t) => t.id === techId);
  if (!tech) return [];

  // Generate realistic jobs matching the technician's stats
  const items: TechnicianJobItem[] = [];
  let jobCounter = 1;

  for (let i = 0; i < tech.jobsStats.inProgress; i++) {
    items.push({
      id: `JOB-2025-${String(jobCounter++).padStart(3, "0")}`,
      clientOrLocation: i % 2 === 0 ? "ฝ่ายผลิต อาคาร A" : "อาคารสำนักงานใหญ่",
      detail: `งาน${tech.role} — ตรวจสอบและแก้ไขระบบ`,
      status: "doing",
      assignedDate: "12 พ.ค. 2568",
      updatedDate: "14 พ.ค. 2568 10:24",
    });
  }

  for (let i = 0; i < tech.jobsStats.assigned; i++) {
    items.push({
      id: `JOB-2025-${String(jobCounter++).padStart(3, "0")}`,
      clientOrLocation: i % 2 === 0 ? "คลังสินค้าส่วนกลาง" : "โรงอาหารและส่วนบริการ",
      detail: `งาน${tech.role} — ได้รับมอบหมายใหม่`,
      status: "assigned",
      assignedDate: "10 พ.ค. 2568",
      updatedDate: "10 พ.ค. 2568 16:37",
    });
  }

  for (let i = 0; i < tech.jobsStats.done; i++) {
    items.push({
      id: `JOB-2025-${String(jobCounter++).padStart(3, "0")}`,
      clientOrLocation: i % 2 === 0 ? "ศูนย์ซ่อมบำรุง อาคาร B" : "ห้องควบคุมกลาง",
      detail: `งาน${tech.role} — บำรุงรักษาแล้วเสร็จ`,
      status: "complete",
      assignedDate: "5 พ.ค. 2568",
      updatedDate: "7 พ.ค. 2568 14:12",
    });
  }

  return items;
}
